### ISSUE TITLE
Bridge UI : Form should support deeplinking URL param `amount` for a better UX

### ISSUE THREAD

**Issue by dewanshparashar** [CoinHippo-Labs/connext-bridge#5]
### Objective
For a seamless user experience, coming to https://bridge.connext.network from other apps, most of the form data should be prefilled from the URL itself. eg. `https://bridge.connext.network/ETH-from-ethereum-to-arbitrum?amount=0.11`

### Reproduce
URL: https://bridge.connext.network/ETH-from-ethereum-to-arbitrum?amount=0.11
The amount is being passed in URL but still the field is empty when the form loads.

<img height="200px" src="https://user-images.githubusercontent.com/7558499/191072485-c67ee975-d222-4218-9991-5c90f2f69fef.png" />

### Code
In the code: `https://github.com/CoinHippo-Labs/connext-bridge/blob/main/components/crosschain-bridge/index.js`, we are extracting `query.amount` from the URL using get query params. However, this value is not being set automatically in the form during any point in the render cycle.

**Comment by pjenviri** [comment]
we've fixed it. thanks.
